# Generated by Django 2.2.16 on 2022-01-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220125_0525'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='constraints_review',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title')},
        ),
    ]
